var express =require("express");
var router  =express.Router();
var passport=require("passport");
var User=require("../models/user");
//HOME PAGE
router.get("/",function(req,res){
  res.render("campgrounds/landing");
});
//USER SIGNUP
router.get("/register",function(req,res){
  res.render("register");
});
router.post("/register",function(req,res){
  var newUser = new User({username:req.body.username});
  User.register(newUser,req.body.password,function(err,user){
    if (err) {
      req.flash("error",err.message);//displays err object ke andar ka message (generated by passport)
      return res.redirect("/register");
    }
    passport.authenticate("local")(req,res,function(){
      req.flash("success","Welcome to YelpCamp "+user.username);
      res.redirect("/campgrounds");
    });
  });
});
//USER LOGIN
router.get("/login",function(req,res){
  res.render("login");
});
router.post("/login",passport.authenticate("local",{
  successRedirect:"/campgrounds",
  failureRedirect:"/login"
}),function(req,res){});
//USER LOGOUT
router.get("/logout",function(req,res){
  req.logOut();
  req.flash("success","Successfully Logged you out");
  res.redirect("/campgrounds");
});
module.exports=router;
